# Generated by Django 5.0.14 on 2026-06-24 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("source_url", models.TextField(unique=True)),
                ("hashed_key", models.CharField(max_length=255, unique=True)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("content", models.TextField()),
                ("thumbnail_url", models.TextField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_live", models.BooleanField(default=False)),
                ("live_poll_url", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articles.mstauthor",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articles.mstarticlecategory",
                    ),
                ),
                (
                    "portal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.mstarticleportal",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "-published_at"],
                        name="articles_ar_categor_82196d_idx",
                    ),
                    models.Index(
                        fields=["portal", "-published_at"],
                        name="articles_ar_portal__032113_idx",
                    ),
                    models.Index(
                        fields=["is_live"], name="articles_ar_is_live_4fb06a_idx"
                    ),
                ],
            },
        ),
    ]
