# Generated by Django 5.0.14 on 2026-06-24 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_articlemedia_articletagmap"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.CharField(max_length=2048)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("rss", "RSS"), ("html", "HTML")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_validation", "Pending validation"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                        ],
                        default="pending_validation",
                        max_length=20,
                    ),
                ),
                ("scrape_interval_minutes", models.PositiveIntegerField(default=30)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "portal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.mstarticleportal",
                    ),
                ),
            ],
        ),
    ]
