# Generated by Django 5.0.14 on 2026-06-24 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_articlesource"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceFetchLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=255)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("on_demand", "On-demand"),
                            ("validation", "Validation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("attempt", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("articles_found", models.PositiveIntegerField(default=0)),
                ("articles_created", models.PositiveIntegerField(default=0)),
                ("articles_updated", models.PositiveIntegerField(default=0)),
                ("articles_unchanged", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fetch_logs",
                        to="articles.articlesource",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "-started_at"],
                        name="articles_so_source__daf2cb_idx",
                    ),
                    models.Index(
                        fields=["status"], name="articles_so_status_899fd2_idx"
                    ),
                    models.Index(
                        fields=["task_id"], name="articles_so_task_id_5f1710_idx"
                    ),
                ],
            },
        ),
    ]
