# Generated by Django 5.0.14 on 2026-06-24 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_sourcefetchlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleRealTimeState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_data", models.JSONField(default=dict)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realtimestate",
                        to="articles.article",
                    ),
                ),
            ],
        ),
    ]
