# Generated by Django 5.0.14 on 2026-07-01 07:10

from django.db import migrations


def create_schedule(apps, schema_editor):
    IntervalSchedule = apps.get_model("django_celery_beat", "IntervalSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    schedule, _ = IntervalSchedule.objects.get_or_create(every=15, period="seconds")
    PeriodicTask.objects.get_or_create(
        name="poll_live_articles",
        task="articles.tasks.poll_live_articles",
        defaults={"interval": schedule, "enabled": True},
    )


def remove_schedule(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name="poll_live_articles").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_articlerealtimestate"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [migrations.RunPython(create_schedule, remove_schedule)]
