# Generated by Django 5.0.14 on 2026-07-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articlesource_parser_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefetchlog',
            name='articles_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articlesource',
            name='parser_mode',
            field=models.CharField(choices=[('rss', 'RSS Feed (summary only)'), ('rss/multistage', 'RSS Feed + Stage 2 full body (trafilatura)'), ('html', 'HTML listing only (card data)'), ('html/multistage', 'HTML multi-stage (trafilatura)'), ('js/playwright', 'JavaScript / Playwright')], default='rss', max_length=20),
        ),
    ]
