# Generated by Django 5.0.14 on 2026-07-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_sourcefetchlog_articles_failed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='llm_clean_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='article',
            name='llm_cleaned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mstarticlecategory',
            name='is_llm_suggested',
            field=models.BooleanField(default=False),
        ),
    ]
